version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile.prod
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG:-21.5-bullseye-slim}
    ports:
      - "8080:8080"
    networks:
      - app-network
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile.prod
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG:-21.5-bullseye-slim}
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"
