kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: set-api-dc-template
labels:
  template: set-api-dc-template

objects:
  kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    name: set-api
    namespace: ec1236-dev
    labels:
      app: set-api
      app.kubernetes.io/component: set-api
      app.kubernetes.io/instance: set-api
      app.kubernetes.io/name: set-api
      app.openshift.io/runtime: set-api
      app.openshift.io/runtime-namespace: ec1236-tools
      app.openshift.io/runtime-version: latest
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - set-api
          from:
            kind: ImageStreamTag
            namespace: ec1236-tools
            name: "set-api:latest"
          lastTriggeredImage: >-
            image-registry.openshift-image-registry.svc:5000/ec1236-tools/set-api@sha256:6b18ee928148d8858ca118fa477c5b0286ffc90f4faa9b36fa311cb7c0e4347e
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: set-api
      deploymentconfig: set-api
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: set-api
          deploymentconfig: set-api
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        containers:
          - name: set-api
            image: >-
              image-registry.openshift-image-registry.svc:5000/ec1236-tools/set-api@sha256:6b18ee928148d8858ca118fa477c5b0286ffc90f4faa9b36fa311cb7c0e4347e
            ports:
              - containerPort: 3000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler

parameters:
  - description: OpenShift Namespace
    displayName: OpenShift Namespace
    name: OPENSHIFT_NAMESPACE
    value: ec1236-dev
    required: true
  - description: Application Name
    displayName: Application Name
    name: APPLICATION_NAME
    required: true
  - description: Image Repository
    displayName: Image Repository
    name: IMAGE_REPOSITORY
    required: true
