kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: set-api-dc-template
  annotations:
    description: Template for deploying the set-api application
    tags: set-api
    openshift.io/display-name: set-api

objects:
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    annotations:
      app.openshift.io/route-disabled: 'false'
      openshift.io/generated-by: OpenShiftWebConsole
    name: set-api
    namespace: ec1236-dev
    labels:
      app: set-api
      app.kubernetes.io/component: set-api
      app.kubernetes.io/instance: set-api
      app.kubernetes.io/name: set-api
      app.openshift.io/runtime: nodejs
      app.openshift.io/runtime-namespace: ec1236-tools
      app.openshift.io/runtime-version: latest
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - set-api
          from:
            kind: ImageStreamTag
            namespace: ec1236-tools
            name: 'set-api:latest'
          lastTriggeredImage: >-
            image-registry.openshift-image-registry.svc:5000/ec1236-tools/set-api@sha256:eda29b7ee2dd659c8a473235baddcf9c4a8638620902103f3c8011f9c8977ad0
      - type: ConfigChange
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: set-api
      deploymentconfig: set-api
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: set-api
          deploymentconfig: set-api
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
      spec:
        containers:
          - name: set-api
            image: >-
              image-registry.openshift-image-registry.svc:5000/ec1236-tools/set-api@sha256:eda29b7ee2dd659c8a473235baddcf9c4a8638620902103f3c8011f9c8977ad0
            ports:
              - containerPort: 3000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: IfNotPresent
            env:
              - name: API_PORT
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: API_PORT
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: DATABASE_URL
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: POSTGRES_USER
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: POSTGRES_PASSWORD
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: POSTGRES_DB
              - name: POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: POSTGRES_HOST
              - name: POSTGRES_PORT
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: POSTGRES_PORT
              - name: FRONTEND_URL
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: FRONTEND_URL
              - name: SSO_AUTH_SERVER_URL
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: SSO_AUTH_SERVER_URL
              - name: SSO_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: SSO_CLIENT_ID
              - name: SSO_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: set-secrets
                    key: SSO_CLIENT_SECRET
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
