name: "E2E Test Run with Playwright"

on:
  workflow_call:
    inputs:
      environment:
        description: "Select Dev or Test environment"
        required: true
        type: string
        default: "APP-Dev"
    secrets:
      SHR_IDIR_PASSWORD:
        required: true
      HM_IDIR_PASSWORD:
        required: true
      ADM_IDIR_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Dev or Test environment"
        required: true
        type: string
        default: "APP-Dev"

jobs:
  e2e-test:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    env:
      SHR_IDIR_USERNAME: ${{ secrets.SHR_IDIR_USERNAME }}
      SHR_IDIR_PASSWORD: ${{ secrets.SHR_IDIR_PASSWORD }}
      HM_IDIR_USERNAME: ${{ secrets.HM_IDIR_USERNAME }}
      HM_IDIR_PASSWORD: ${{ secrets.HM_IDIR_PASSWORD }}
      ADM_IDIR_USERNAME: ${{ secrets.ADM_IDIR_USERNAME }}
      ADM_IDIR_PASSWORD: ${{ secrets.ADM_IDIR_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Test Command
        run: |
          if [[ "${{ inputs.environment }}" == "APP-Dev" ]]; then
            echo "TEST_CMD=npm run playwright-dev" >> $GITHUB_ENV
          else
            echo "Error: Unknown environment '${{ inputs.environment }}'" >&2
            exit 1
          fi

      - name: Echo Test Command
        run: echo $TEST_CMD

      - name: Navigate to e2e folder and Install Dependencies
        run: |
          cd src/e2e
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright Test
        run: |
          cd src/e2e
          $TEST_CMD

      - name: Create Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./src/e2e/playwright-report/
          retention-days: 30
