name: Pull Request — API Unit Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "api/**"

jobs:
  check-for-tests:
    runs-on: ubuntu-latest
    outputs:
      has-tests: ${{ steps.check-for-tests.outputs.has-tests }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install yq
        run: |
          sudo add-apt-repository -y ppa:rmescandon/yq
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Get test file naming convention
        id: get-naming-convention
        run: |
          echo "test-naming-convention=$(yq -e '.test-naming-convention' .github/helpers/test-config.yaml)" >> $GITHUB_OUTPUT

      - name: Check for tests
        id: check-tests
        run: |
          echo "has-tests=$(if find api/tests -name '${{ steps.get-pattern.outputs.test-naming-convention }}'; then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT
  run-tests:
    needs: check-for-tests
    if: ${{ needs.check-for-tests.outputs.has-tests == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          cd api
          npm install
          npm test
