name: Pull Request — Frontend Image Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  SET-Frontend-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Create api/.env file
      - name: Create .env file
        run: |
          touch api/.env

      # Build Frontend Image
      - name: Build Frontend Image
        run: |
          docker-compose -f docker-compose.dev.yaml build frontend
