name: Pull Request — API Image Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
  push:
    branches: [ main ]
    paths:
      - 'api/**'

jobs:
  SET-API-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Environment Variables
      - name: Setup Environment Variables
        run: |
          touch api/.env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> api/.env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> api/.env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> api/.env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> api/.env
          echo "API_PORT=${{ secrets.API_PORT }}" >> api/.env

      # Build API Image
      - name: Build API Image
        run: |
          docker-compose -f docker-compose.dev.yaml build api
