name: Pull Request — API Image Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'api/**'
  push:
    branches: [ main ]
    paths:
      - 'api/**'

jobs:
  SET-API-build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Setup Environment Variables
      - name: Setup Environment Variables
        run: |
          touch .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "API_PORT=${{ secrets.API_PORT }}" >> .env

      # Build API Image
      - name: Build API Image
        run: |
          docker-compose build api
